services:
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - DATABASE_URL="file:./perctice.db"
      - REDIS_HOST=redis
      - REDIS_PORT=6379
